### ISSUE TITLE
New-AzureRmADApplication

### ISSUE THREAD

**Issue by chintan3100** [Azure/azure-docs-powershell#323]
New ad application using powershell and certificate authentication not working

$certificateFilePath = "D:\cert\ADTestVaultApplication.cer"
$certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$certificate.Import($certificateFilePath)
$rawCertificateData = $certificate.GetRawCertData()
$credential = [System.Convert]::ToBase64String($rawCertificateData)
$startDate= [System.DateTime]::Now
$endDate = $startDate.AddYears(1)
$adApplication = New-AzureRmADApplication -DisplayName "CerFDSFtAdApplication" -HomePage  "http://www.test.com" -IdentifierUris "http://www.test.com" -CertValue $credential  -StartDate $startDate -EndDate $endDate

**Comment by TaraMeyer** [comment]
@chintan3100 - thank you for reporting this issue.  Please file this issue at the source code repo as that is the channel that the devs monitor and fix issue such as this.  The Azure source code repo is here:  https://github.com/Azure/azure-powershell.  The repo that you initially reported this issue is the content repo only and we are unable to make the fixes to the code that it seems your issue deserves.
