### ISSUE TITLE
No content in Set-AzureStorageCORSRule

### ISSUE THREAD

**Issue by sowmitranalla** [Azure/azure-docs-powershell#371]
Hi, 

There doesn't seem to be any content in this documentation. Can someone update the records?

https://github.com/Azure/azure-docs-powershell/blob/master/azureps-cmdlets-docs/Storage/Azure.Storage/v1.0.4.3/Set-AzureStorageCORSRule.md

https://docs.microsoft.com/en-us/powershell/module/azure.storage/set-azurestoragecorsrule?view=azurermps-1.2.9

**Comment by TaraMeyer** [comment]
Hi @sowmitranalla - you can always try to toggle to other versions of the doc set in order to locate more complete content.  I found more content on this topic in version 1.7 (https://docs.microsoft.com/en-us/powershell/module/azure.storage/Set-AzureStorageCORSRule?view=azurermps-1.7.0) and will add to the backlog to have some filling in the blanks for 1.2.9.  Thank you for reporting this!

**Comment by TaraMeyer** [comment]
@sowmitranalla - closing this issue now.  Please let me know if you have any other questions.

**Comment by sowmitranalla** [comment]
@TaraMeyer I later saw the updated version of the docs. Thanks for looking into this,

**Comment by TaraMeyer** [comment]
@sowmitranalla - You are most welcome!
