### ISSUE TITLE
Add-AzureKeyVaultManagedStorageAccount   active key  explanation

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-docs-powershell#469]
Can somebody explain the active key functionality in  `Add-AzureKeyVaultManagedStorageAccount `.   If i set regenerationPeriod as 1 day and active key as `key1`.  Then which key will be changed after regenerationPeriod and what happens to the other key value. Would it be invalidated? Can i use other key in PowerBI or storage explorer to access the storage account ?

 What is the meaning of `This auto regeneration process will continue between 'key1' and 'key2' with a gap of 90 days` ?

I asked more questions about this in SO. No response yet. Please answer those questions as well.  SO Link https://stackoverflow.com/questions/47776434/azure-managed-storage-account-keys

**Comment by TaraMeyer** [comment]
Hello @prabhakarreddy1234 - all good questions.  @cabailey might you be able to answer the above question on the active key functionality?

**Comment by cabailey** [comment]
Hi @prabhakarreddy1234  - I'm no longer the writer for these PowerShell cmdlets, so looping in @barclayn and @amitbapat

**Comment by TaraMeyer** [comment]
@barclayn and @amitbapat  - can you please provide the details requested above?

**Comment by amitbapat** [comment]
@Rashmi Jha<mailto:rashmij@microsoft.com> – can you please help here?

**Comment by TaraMeyer** [comment]
@amitbapat - is there another person that can assist?  This issue has been open for over 60 days.

**Comment by amitbapat** [comment]
+ @Rashmi Jha<mailto:rashmij@microsoft.com>

**Comment by rashmi-jha** [comment]
The key set as active/primary key won't be the one which is rotated. It will rotate the secondary key.  You will be able to use tokens returned by Azure Key Vault using the active key.  If you directly use the active key or secondary key i.e. through Storage interfaces then Azure Key Vault wouldn't know which one is the active one. 
Azure key vault will use the active key to issue SAS tokens and rotate the secondary key which doesn't have any valid tokens. After rotation of secondary key it will start issuing tokens from secondary key and rotate the primary key when all its tokens have expired. 

regenerationPeriod tells how often you want to rotate. 

What is the meaning of This auto regeneration process will continue between 'key1' and 'key2' with a gap of 90 days ?
-I need more context to answer this question.

**Comment by rijethma** [comment]
I still see keys for this storage account in azure portal. Are they invalid ? or will they change every time keyvault regenerates keys for this storage account?
- they are valid keys, they'll change as key vault regenerates the keys.

I had set -ActiveKeyName Key2. Each time i regenerate the key Key1 is being regenerated. If Key1 is regenerated then is Key2 still valid even after 1 day? This active key concept is not so clear in the documentation. Can someone explain it.
- when we auto rotate i.e. key vault rotates the keys when regeneration time comes (which is based in RegenerationPeriod), we always rotate the inactive key and mark it as current active key because we don't want to invalidate all the sas tokens you might have generated using old active key.

here is a small scenario for better understanding:
-	User sets an active key name (KEY1) while onboarding
-	User also sets regeneration period (30 DAYS) for the storage key
-	When the regeneration time comes (AFTER 30 DAYS), we regenerate the inactive key (KEY2) and mark it as current active key
-	We keep the previous active key (KEY1) as it as and mark it as inactive key
-	When the second regeneration time comes we regenerate the inactive key (KEY1) and mark it as new active key
-	And the process goes on…


Is Sas token the only way to get access to storage account resources. I just want to have full access to storage account for the regeneration period. is it possible without using Sas token?
- if you use the storage account key you'll get full admin access on storage account

I created SAS Definition from powershell and create SAS token out of it whenever i want to access Storage account. I think SAS Token would be invalidated but not SAS Definion. I am assuming i don't have to handle expiry in the code because i always get new SAS Token. Am i doing it correctly?
- yes, when the sas token expires, you just generate a new one. and sas definitions don't expire

**Comment by TaraMeyer** [comment]
@prabhakarreddy1234 - does this solve the issue for you?
