### ISSUE TITLE
Broken Links to Azure Cmdlets

### ISSUE THREAD

**Issue by doctordns** [Azure/azure-docs-powershell#472]
I noticed in the build report of a recent PR, there were several warnings about invalid file links. as follows:

| In | Bad Link |
| --- | --- |
| azurermps-4.4.1/AzureRM.Compute/Add-AzureRmVMNetworkInterface.md | Invalid file link to ~/azurermps-4.4.1/AzureRM.Compute/Get-AzureRmNetworkInterface.md |
| azurermps-4.4.1/AzureRM.Compute/Add-AzureRmVMSecret.md | Invalid file link to ~/azurermps-4.4.1/AzureRM.Compute/Set-AzureKeyVaultSecret.md |
| azurermps-4.4.1/AzureRM.Compute/Add-AzureRmVmssSecret.md | Invalid file link to ~/azurermps-4.4.1/AzureRM.Compute/Set-AzureKeyVaultSecret.md |
| azurermps-5.0.0/AzureRM.Compute/Add-AzureRmVMNetworkInterface.md | Invalid file link to ~/azurermps-5.0.0/AzureRM.Compute/Get-AzureRmNetworkInterface.md |
 |azurermps-5.0.0/AzureRM.Compute/Add-AzureRmVMSecret.md | Invalid file link to ~/azurermps-5.0.0/AzureRM.Compute/Set-AzureKeyVaultSecret.md|
| azurermps-5.0.0/AzureRM.Compute/Add-AzureRmVmssSecret.md | Invalid file link to ~/azurermps-5.0.0/AzureRM.Compute/Set-AzureKeyVaultSecret.md|

I would have just fixed this, but I have some questions how to implement fixes.

In each of the source documents for which there are the warnings, the document contains a link to an MD file in azure/azure-docs-powershell, however, the file does not exist (hence the warning!). 

Looking at the first example, for some reason,  the Get-AzureRmNetworkInterface.md is not in the right place. 

Looking at the web, the 4.4.1 online version of Get-AzureRmNetworkINterface (at https://docs.microsoft.com/en-us/powershell/module/azurerm.network/get-azurermnetworkinterface?view=azurermps-4.4.1), if I click on Edit it takes me to a different location in Github. It shows the relevant md file is at azure/azure-powershell/src/ResourceManager/Network/Commands.Network/help/Get-AzureRmNetworkInterface.md.

I am guessing that somewhere/somehow, the documentation for a few cmdlets was left under azure/azure-powershell/src, rather than azure/azure-docs-powershell. If that makes sense. 

To fix this, I see two options:
1. In the documents with warnings, change the reference to point to a web location for the relevant documentation (eg pointing directly to https://docs.microsoft.com/en-us/powershell/module/azurerm.network/get-azurermnetworkinterface?view=azurermps-4.4.1 rather than to an MD document on GitHub.

2. Assuming this was just a few files not migrated correctly, then the fix seems to be to move the relevant MD files from azure/azure-powershell to azure/azure-docs-powershell so that the 6 documents no longer generate an error message as they now DO point to a valid file.

Happy to try to fix this if someone gives a steer about which approach to take.

**Comment by TaraMeyer** [comment]
@doctordns - thank you for reaching out and apologies for the delay in response.  The desired behavior is that any time a customer chooses to edit an Azure PowerShell reference topic, the user will land in the source repo.  The reason for this is because the Azure src repo is the one source of truth.  The Azure docs repo ingests docs from the src via a CI for every msi release.  However, there were cases, in past releases, where we had to manual support modules and topics.  In this scenario, the topics do not tie back to the src repo as they were not properly tagged during the CI due to our manual intervention.  If you would like to make changes to these links, may I suggest that you make all the updates in the src repo.  This will insure that the changes will flow into the content repo with the next release.  If you also desire to update the prior version of docs, you will then need to submit a pr to the content repo.  The content repo maintains the prior releases, the src repo is always working in real time and on the latest and greatest.

**Comment by sdwheeler** [comment]
Submitted PR #487
