### ISSUE TITLE
Checking which versions are installed

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-docs-powershell#633]
It would be helpful to include an example of how to check the version(s) that is/are installed, e.g.
Import-Module AzureRM
Get-Module -Name AzureRM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 140cfec3-6b83-ceac-f220-94319dc78d67
* Version Independent ID: a1f76299-1832-cd86-b4f5-f7635ed62492
* Content: [Install Azure PowerShell on Windows with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-azurerm-ps?view=azurermps-6.3.0)
* Content Source: [docs-conceptual/azurermps-6.3.0/install-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.3.0/install-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
What would be the reason for needing this information during the install process?

**Comment by sptramer** [comment]
The `Update-Module` command doesn't require any specific version information, and is safe to run at pretty much any point. Your comment about being able to look up the installed versions is both important for loading specific versions or our uninstall instructions though, and will be added there.

**Comment by cbailiss** [comment]
Thanks.  Re: the Update-Module command - as you say, it doesn't require specific version information.  I was referring to me wanting to work out whether I need to run the command or not.  Maybe I am in the minority, but I prefer to know the version I have before I run an update.  I don't like running commands blind.

**Comment by sptramer** [comment]
@sdwheeler Is it common for PowerShell users to want to check version information before running any module upgrades? This isn't a standard practice I've seen with any other package management system I've used.

**Comment by sdwheeler** [comment]
@sptramer - Yes it is common. I had instructions in the setup article to check your version of PowerShellGet. Because there are version requirements to have the -AllowClobber parameter. It looks like you took it out. I must have missed that deletion in the review.

**Comment by sptramer** [comment]
I originally took them out because `Update-Module` does not require `-AllowClobber` that I could see, and no `Install-Module` run did either. Are there particular environment configurations I need to be testing to make sure that issues like these are caught?

**Comment by sdwheeler** [comment]
Install-Module will require -AllowClobber if there is another version of the module already installed. Here is the common scenario.

1. Install AzureRM vX.0 using the MSI or WebPI. You use this for sometime and don't really remember how you installed.
2. A new version is released.
3. You try to run `Update-Module`. That fails because there is not a version of AzureRM that was installed using PowerShellGet.
4. You run `Install-Module` to install the latest version from the Gallery. That fails telling you to use **AllowClobber** because an older version exists on the system.

If you are running the version of PowerShellGet that shipped in Windows 10, you don't have a version that supports AllowClobber. `Get-Module` shows you the versions you have installed on your system.

```powershell
PS C:\Users\SWHEELER\Desktop> Get-Module PowerShellGet,PackageManagement -list | select Name,Version

Name              Version
----              -------
PackageManagement 1.1.7.2
PackageManagement 1.0.0.1
PowerShellGet     1.6.5
PowerShellGet     1.0.0.1
```
The 1.0.0.1 versions of these modules ship in Windows 10 and cannot be uninstalled. Since they were not installed using PowerShellGet you cannot use `Update-Module` to get the new version. You have to use `Install-Module`.

**Comment by sptramer** [comment]
Now that we have uninstall instructions, it seems like this is much more easily handled by directing users to uninstall their old MSI/WebPI install (which is easy to see if the install was done this way) rather than encouraging use of a destructive feature like `-AllowClobber`. It also keeps the documentation shorter.

**Comment by sdwheeler** [comment]
You will get support feedback asking about that error message. It needs to be in the troubleshooting section at least. Also, -AllowClobber is not "destructive". Each version is installed in its own version folder. The old version is not overwritten. Its just that the latest version has load preference when you Import the module.

**Comment by sptramer** [comment]
OK, that actually wasn't clear from the documentation (`-AllowClobber` implies a destructive operation in its name, and the PowerShell docs don't say _what's_ clobbered.) It sounds like a lot of pain can be resolved by adding this back in, along with the requirement for 1.6.5 PowerShellGet.
