### ISSUE TITLE
Additional automation

### ISSUE THREAD

**Issue by aaronr93** [Azure/azure-docs-powershell#778]
Thank you for the excellent script! 

Re: the script provided to use the function, is there a way to automate it so that all versions, or even all versions that are not the latest, are uninstalled? Right now it is hardcoded as 4.4.1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4840e6a2-9821-e400-06d4-5ad951b1fcac
* Version Independent ID: 9a312576-d1c8-6a00-c1ff-b52677b16e17
* Content: [Uninstall Azure PowerShell](https://docs.microsoft.com/en-us/powershell/azure/uninstall-azurerm-ps?view=azurermps-6.10.0)
* Content Source: [docs-conceptual/azurermps-6.10.0/uninstall-azurerm-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.10.0/uninstall-azurerm-ps.md)
* Product: **powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@aaronr93 - Try modifying the script to use any of these [Uninstall-Module](https://docs.microsoft.com/en-us/powershell/module/powershellget/uninstall-module?view=powershell-6) arguments:

* `-AllVersions` - to remove all
* `-MaximumVersion` - you will need to look up the most recent version, and then set this value to the version __before__ that.

To get the latest version only, just use `Get-InstalledModule AzureRM`.

Sorry that there's not a better script for this, but it would be difficult to do without complicating the logic a great deal to do proper detection of the latest version, then degrade it properly so that only earlier versions are removed.

(cc @sdwheeler if he has a better option or thought, since he wrote the original version of this script.)

**Comment by sdwheeler** [comment]
@aaronr93 The script is not hardcoded to a specific version. The example usage shows uninstalling v4.4.1. The script is designed to uninstall a specific version, but you tell it which version to remove. The example @sptramer shows for removing all versions is valid.
