### ISSUE TITLE
Please clarify what happens if AzureRM is not uninstalled

### ISSUE THREAD

**Issue by DaveEM** [Azure/azure-docs-powershell#818]
This documentation says, "In order to install the Az module, AzureRM must be uninstalled", but I didn't realize I had AzureRM installed until after I installed the Az module and the Az module install did not fail.  This leaves me with a couple questions:

1. What are the consequences of having both installed side-by-side?
2. Does uninstalling AzureRM after installing the Az module have any negative side effects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036dda1c-9f8d-35e2-eb53-5d3c235b429f
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [Install Azure PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azurermps-6.12.0#feedback)
* Content Source: [docs-conceptual/azurermps-6.12.0/install-az-ps.md](https://github.com/Azure/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.12.0/install-az-ps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by sptramer** [comment]
@DaveEM - Information will be added to the documentation, but to answer your questions:

1. The modules can, in fact, coexist. The issue comes when you enable aliases for `Az`, which conflict with the `AzureRM` cmdlet names and might result in unspecified behavior.
2. You can uninstall either module at any time. Right now our recommendation is to uninstall `AzureRM` and try out the `Az` module while enabling compatibility aliases with `Enable-AzureRMAlias`.
